vim.lsp.enable('pyright')
vim.lsp.enable('gopls')
vim.lsp.enable('lua_ls')
vim.lsp.enable('tsserver')
vim.lsp.enable('biome')
vim.lsp.enable('svelte')
vim.lsp.enable('clangd')
vim.lsp.enable('rust_analyzer')
vim.lsp.enable('golangci_lint_ls')

